In [2]:
import numpy as np

In [7]:
L = np.random.random(100)
sum(L)

np.float64(47.399389925978724)

In [8]:
np.sum(L)

np.float64(47.39938992597873)

In [9]:
big_array = np.random.rand(10000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

470 ms ± 2.11 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
6.86 ms ± 109 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [11]:
min(big_array) , max(big_array)

(np.float64(1.4426320582572316e-08), np.float64(0.9999999989459689))

In [14]:
%timeit min(big_array)
%timeit np.min(big_array)

284 ms ± 2.72 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
2.65 ms ± 66.1 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [16]:
print(big_array.min(), big_array.max(), big_array.sum())

1.4426320582572316e-08 0.9999999989459689 5000467.965146787


In [17]:
M = np.random.random((3,4))

In [18]:
print(M)

[[0.29644743 0.26125502 0.72584205 0.07099698]
 [0.63735896 0.56344665 0.09040655 0.55281073]
 [0.79141712 0.80260276 0.67718066 0.41723084]]


In [25]:
M.sum()

np.float64(5.88699576200874)

In [23]:
M.sum(axis= 0)

array([1.72522352, 1.62730443, 1.49342926, 1.04103855])

In [24]:
np.add.reduce(M)

array([1.72522352, 1.62730443, 1.49342926, 1.04103855])

In [26]:
M.min(axis=0)

array([0.29644743, 0.26125502, 0.09040655, 0.07099698])

In [27]:
M.min()

np.float64(0.07099698210447725)

In [28]:
M.max(axis=1)

array([0.72584205, 0.63735896, 0.80260276])