In [36]:
import numpy as np

In [37]:
np.__version__

'2.3.1'

In [ ]:
np

SyntaxError: invalid syntax (2537469125.py, line 1)

In [40]:
np?

Type:        module
String form: <module 'numpy' from 'C:\\Users\\Safty Obaid\\AppData\\Roaming\\Python\\Python313\\site-packages\\numpy\\__init__.py'>
File:        c:\users\safty obaid\appdata\roaming\python\python313\site-packages\numpy\__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicat

In [2]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [3]:
np.array([1,2,3,4,5.4])

array([1. , 2. , 3. , 4. , 5.4])

In [4]:
np.array([1,2,3,4,5,6],dtype='float32')

array([1., 2., 3., 4., 5., 6.], dtype=float32)

In [5]:
np.array([range(i,i+3) for i in[3,5,7]])

array([[3, 4, 5],
       [5, 6, 7],
       [7, 8, 9]])

In [8]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [9]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [10]:
np.ones((3,5),dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [12]:
np.full((3,5),4.44)

array([[4.44, 4.44, 4.44, 4.44, 4.44],
       [4.44, 4.44, 4.44, 4.44, 4.44],
       [4.44, 4.44, 4.44, 4.44, 4.44]])

In [14]:
np.arange(3,30,3)

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27])

In [16]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [19]:
np.random.random((3,4))

array([[0.59326178, 0.95521425, 0.21919306, 0.49701803],
       [0.70263023, 0.57679948, 0.75578872, 0.31430958],
       [0.14163696, 0.15551042, 0.27937871, 0.54997777]])

In [20]:
np.random.normal(0,1,(3,3))

array([[ 0.52912299, -0.47557636, -0.73188413],
       [ 0.5635745 , -0.16916884,  1.20371398],
       [-1.06770604,  0.6990849 ,  0.80065345]])

In [21]:
np.random.randint(0,10,(3,5))

array([[7, 2, 4, 9, 8],
       [8, 6, 0, 0, 5],
       [2, 7, 7, 2, 5]], dtype=int32)

In [23]:
np.eye(4,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [24]:
np.eye(4,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [25]:
np.empty(3)

array([ 0.,  5., 10.])

In [26]:
np.empty(3)

array([ 0.,  5., 10.])

In [29]:
np.zeros(10,dtype='int16')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [30]:
np.zeros(10,dtype=np.int32)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)