In [2]:
import numpy as np

In [3]:
x = np.array([1,2,3,4,5])

In [4]:
x < 3

array([ True,  True, False, False, False])

In [5]:
x > 3

array([False, False, False,  True,  True])

In [6]:
x <= 3

array([ True,  True,  True, False, False])

In [7]:
x >= 3

array([False, False,  True,  True,  True])

In [8]:
x != 3

array([ True,  True, False,  True,  True])

In [9]:
x == 3

array([False, False,  True, False, False])

In [10]:
(2 * x) == (x ** 2)

array([False,  True, False, False, False])

In [11]:
rng = np.random.RandomState(0)
x = rng.randint(10, size=(3,4))
x

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]], dtype=int32)

In [12]:
x > 6

array([[False, False, False, False],
       [ True,  True, False, False],
       [False, False,  True, False]])

In [13]:
x

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]], dtype=int32)

In [14]:
np.count_nonzero(x > 6)

np.int64(3)

In [15]:
np.sum(x > 6)

np.int64(3)

In [17]:
np.sum(x > 6,axis = 1)

array([0, 2, 1])

In [18]:
np.any(x>8)

np.True_

In [19]:
np.any(x<8)

np.True_

In [20]:
np.all(x>8)

np.False_

In [21]:
np.all(x==8)

np.False_

In [22]:
np.all(x<8,axis=1)

array([ True, False,  True])

In [23]:
np.sum((x > 6) & (x < 8))

np.int64(2)

In [24]:
np.sum(~(x > 6) & (x < 8))

np.int64(9)

In [25]:
x

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]], dtype=int32)

In [26]:
x[x<5]

array([0, 3, 3, 3, 2, 4], dtype=int32)

In [27]:
bool(42) , bool(0)

(True, False)

In [29]:
bool(42 & 0)

False

In [30]:
bool(42 and 0)

False

In [31]:
bool(42 or 0)

True

In [32]:
bool(42 | 0)

True

In [33]:
bin(42)

'0b101010'

In [34]:
bin(59)

'0b111011'

In [35]:
bin(42&59)

'0b101010'

In [37]:
bin(42|59)

'0b111011'

In [39]:
bin(42 and 59)

'0b111011'

In [40]:
bin(42 or 59)

'0b101010'

In [47]:
a = np.array([1,0,1,0,1,0])
b = np.array([1,1,1,0,1,1])
a | b


array([1, 1, 1, 0, 1, 1])

In [48]:
a or b

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [50]:
x = np.arange(10)
(x > 4) & (x < 8)

array([False, False, False, False, False,  True,  True,  True, False,
       False])

In [51]:
(x > 4) and (x < 8)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()