In [1]:
import numpy as np

In [2]:
rand = np.random.RandomState(42)

x = rand.randint(100, size = 10)
print(x)

[51 92 14 71 60 20 82 86 74 74]


In [5]:
[x[3],x[7],x[2]]

[np.int32(71), np.int32(86), np.int32(14)]

In [6]:
ind = [3,7,4]
x[ind]

array([71, 86, 60], dtype=int32)

In [8]:
ind = np.array([[3,7],
               [4,5]])
x[ind]

array([[71, 86],
       [60, 20]], dtype=int32)

In [14]:
x = np.arange(12).reshape((3,4))
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [16]:
row = np.array([0,1,2])
col = np.array([2,1,3])
x[row,col]

array([ 2,  5, 11])

In [17]:
x[row[:,np.newaxis],col]

array([[ 2,  1,  3],
       [ 6,  5,  7],
       [10,  9, 11]])