In [2]:
import numpy as np

In [3]:
np.random.seed(0)
x1 = np.random.randint(10,size=6)
x2 = np.random.randint(10,size=(3,4))
x3 = np.random.randint(10,size=(3,4,5))

In [4]:
print(x1.ndim)
print(x1.shape)
print(x1.size)

1
(6,)
6


In [5]:
print(x3.ndim)
print(x3.shape)
print(x3.size)

3
(3, 4, 5)
60


In [6]:
print(x2.ndim)
print(x2.shape)
print(x2.size)

2
(3, 4)
12


In [7]:
print(x3.dtype)

int32


In [8]:
print(x3.itemsize)
print(x3.nbytes)

4
240


In [9]:
print(x2.itemsize)
print(x2.nbytes)

4
48


In [10]:
print(x1.itemsize)
print(x1.nbytes)

4
24


In [11]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
x[:5]

array([0, 1, 2, 3, 4])

In [13]:
x[5:]

array([5, 6, 7, 8, 9])

In [14]:
x[4:7]

array([4, 5, 6])

In [15]:
x[::2]

array([0, 2, 4, 6, 8])

In [16]:
x[1::2]

array([1, 3, 5, 7, 9])

In [17]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [18]:
x[5::-2]

array([5, 3, 1])

In [19]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]], dtype=int32)

In [20]:
x2[:2,:3]

array([[3, 5, 2],
       [7, 6, 8]], dtype=int32)

In [21]:
x2[:3,::2]

array([[3, 2],
       [7, 8],
       [1, 7]], dtype=int32)

In [22]:
x2[::-1,::-1]

array([[7, 7, 6, 1],
       [8, 8, 6, 7],
       [4, 2, 5, 3]], dtype=int32)

In [23]:
print(x2[:,0])

[3 7 1]


In [24]:
print(x2[:,2])

[2 8 7]


In [25]:
print(x2[0,:])

[3 5 2 4]


In [26]:
print(x2[0])

[3 5 2 4]


In [27]:
print(x2)

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]


In [28]:
x2_sub = x2[:2,:2]
x2_sub

array([[3, 5],
       [7, 6]], dtype=int32)

In [29]:
x2_sub[0,0] = 99
x2_sub

array([[99,  5],
       [ 7,  6]], dtype=int32)

In [30]:
x2

array([[99,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]], dtype=int32)

In [31]:
x2_sub_copy = x2[:2,:2].copy()
x2_sub_copy

array([[99,  5],
       [ 7,  6]], dtype=int32)

In [33]:
x2_sub_copy[0,0] = 42
x2_sub_copy

array([[42,  5],
       [ 7,  6]], dtype=int32)

In [35]:
x2

array([[99,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]], dtype=int32)

In [43]:
x4 = np.arange(1,10).reshape(3,3)
x4

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [55]:
x = np.array([1,2,3])
x

array([1, 2, 3])

In [56]:
x5 = x.reshape((1,3))
x5

array([[1, 2, 3]])

In [57]:
x6 = x.reshape((3,1))
x6

array([[1],
       [2],
       [3]])

In [58]:
x[np.newaxis, :]

array([[1, 2, 3]])

In [59]:
x[:,np.newaxis]

array([[1],
       [2],
       [3]])

In [61]:
x = np.array([1,2,3])
y = np.array([4,5,6])
z = np.array([7,8,9])
np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
grid = np.array([[1,2,3],
                [4,5,6]])

In [63]:
np.concatenate([grid,grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [64]:
np.concatenate([grid,grid], axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [65]:
x = np.array([1,2,3])
grid = np.array([[9,8,7],
                 [5,6,7]])

In [66]:
np.vstack([x,grid])

array([[1, 2, 3],
       [9, 8, 7],
       [5, 6, 7]])

In [68]:
y = np.array([[99],
              [99]])
np.hstack([y,grid])

array([[99,  9,  8,  7],
       [99,  5,  6,  7]])

In [69]:
x = [1,2,3,4,5,6,7,8,9]
x1,x2,x3 = np.split(x,[3,5])
print(x1,x2,x3)

[1 2 3] [4 5] [6 7 8 9]


In [71]:
grid = np.arange(16).reshape((4,4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [75]:
upper,lower = np.vsplit(grid,[2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [76]:
left,right = np.hsplit(grid,[2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [77]:
import platform
print(platform.python_implementation())


CPython
