In [1]:
import numpy as np

In [2]:
np.random.seed(0)
def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0/ values[i]
    return output

values = np.random.randint(1,10,size = 5)
values
compute_reciprocals(values)

array([0.16666667, 1.        , 0.25      , 0.25      , 0.125     ])

In [6]:
big_array = np.random.randint(1,100,size = 1000000)
%time compute_reciprocals(big_array)

CPU times: total: 1.28 s
Wall time: 1.29 s


array([0.02857143, 0.01052632, 0.01886792, ..., 0.02083333, 0.01136364,
       0.04      ], shape=(1000000,))

In [7]:
%timeit (1.0/big_array)

1.74 ms ± 11 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [8]:
np.arange(5) / np.arange(1,6)

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])