In [2]:
import numpy as np

In [3]:
np.random.seed(0)
def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0/ values[i]
    return output

values = np.random.randint(1,10,size = 5)
values
compute_reciprocals(values)

array([0.16666667, 1.        , 0.25      , 0.25      , 0.125     ])

In [4]:
big_array = np.random.randint(1,100,size = 1000000)
%time compute_reciprocals(big_array)

CPU times: total: 1.34 s
Wall time: 1.34 s


array([0.1       , 0.01190476, 0.04545455, ..., 0.01428571, 0.01098901,
       0.01149425], shape=(1000000,))

In [5]:
%timeit (1.0/big_array)

1.8 ms ± 11.4 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [6]:
np.arange(5) / np.arange(1,6)

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

In [ ]:
x = np.arange(9).reshape((3,3))  # x = np.arange(9).reshape(3,3) also same
2 ** x

array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]])

In [15]:
x = np.arange(4)
print(x)
print(x+5)
print(x-5)
print(x*5)
print(x/5)
print(x//5)
print(-x)
print(x**5)
print(x%5)

[0 1 2 3]
[5 6 7 8]
[-5 -4 -3 -2]
[ 0  5 10 15]
[0.  0.2 0.4 0.6]
[0 0 0 0]
[ 0 -1 -2 -3]
[  0   1  32 243]
[0 1 2 3]


In [16]:
-(0.5*x + 1) ** 2

array([-1.  , -2.25, -4.  , -6.25])

In [19]:
print(np.add(x,5))
print(np.subtract(x,5))
print(np.negative(-x))
print(np.multiply(x,5))
print(np.divide(x,5))
print(np.floor_divide(x,5))
print(np.power(x,5))
print(np.mod(x,5))

[5 6 7 8]
[-5 -4 -3 -2]
[0 1 2 3]
[ 0  5 10 15]
[0.  0.2 0.4 0.6]
[0 0 0 0]
[  0   1  32 243]
[0 1 2 3]


In [22]:
x = np.array([-1,-2,-3,-4,-5])
abs(x)

array([1, 2, 3, 4, 5])

In [23]:
np.absolute(x)

array([1, 2, 3, 4, 5])

In [24]:
np.abs(x)

array([1, 2, 3, 4, 5])

In [28]:
x = np.array([3-4j,4-3j,2+0j,0+1j])
np.abs(x) #returns magnitude

array([5., 5., 2., 1.])

In [30]:
theta = np.linspace(0,np.pi,3)
print(theta)
print(np.sin(theta))
print(np.cos(theta))
print(np.tan(theta))

[0.         1.57079633 3.14159265]
[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [31]:
x = np.array([-1,0,1])
print(x)
print(np.arcsin(x))
print(np.arccos(x))
print(np.arctan(x))

[-1  0  1]
[-1.57079633  0.          1.57079633]
[3.14159265 1.57079633 0.        ]
[-0.78539816  0.          0.78539816]


In [32]:
x = np.array([1,2,3])
print(x)
print(np.exp(x))
print(np.exp2(x))
print(np.power(3,x))

[1 2 3]
[ 2.71828183  7.3890561  20.08553692]
[2. 4. 8.]
[ 3  9 27]


In [33]:
x = [1,2,4,10]
print(np.log(x))
print(np.log2(x))
print(np.log10(x))


[0.         0.69314718 1.38629436 2.30258509]
[0.         1.         2.         3.32192809]
[0.         0.30103    0.60205999 1.        ]


In [34]:
x = [0,0.001,0.01,0.1]
print(np.expm1(x))
print(np.log1p(x))

[0.         0.0010005  0.01005017 0.10517092]
[0.         0.0009995  0.00995033 0.09531018]


In [36]:
from scipy import special

In [37]:
x = np.array([1,5,10])
print(special.gamma(x))
print(special.gammaln(x))
print(special.beta(x,2))

[1.0000e+00 2.4000e+01 3.6288e+05]
[ 0.          3.17805383 12.80182748]
[0.5        0.03333333 0.00909091]


In [38]:
x = np.array([0,0.3,0.7,1.0])
print(special.erf(x))
print(special.erfc(x))
print(special.erfinv(x))

[0.         0.32862676 0.67780119 0.84270079]
[1.         0.67137324 0.32219881 0.15729921]
[0.         0.27246271 0.73286908        inf]


In [39]:
x = np.arange(5)
y = np.empty(5)
np.multiply(x,10, out = y)
print(y)

[ 0. 10. 20. 30. 40.]


In [40]:
y = np.zeros(10)
np.power(2,x,out=y[::2])
print(y)

[ 1.  0.  2.  0.  4.  0.  8.  0. 16.  0.]


In [43]:
x = np.arange(1,6)
np.add.reduce(x)
print(x)

[1 2 3 4 5]
